fix: change tofu unpacking to default to terraform registry
cloudfoundry/cloud-service-broker pull request #1001
Opened 2024-04-08 16:15 UTC by pivotal-marcela-campo

We are keeping the default provider registry as terraform's own registry for now instead
of switching to OpenTofu's. We had done this during `pak` but had still defaulting to opentofu registry
when unpacking which caused 
* the state to contained references to opentofu's registry instead, and 
* the terraform provider to unpak under a `registry.opentofu.org` directory instead of the expected `registry.terraform.io` directory.

With this change we expect to have only references to registry.terraform.io unless otherwise specified by the brokerpak both in 
* the state and 
* directory structure

### Checklist:

* [x] Have you added or updated tests to validate the changed functionality?
* [ ] Have you added Release Notes in the docs repositories?
* [x] Have you followed the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)?

2024-04-08 16:39 UTC, blgm requested changes
In the comment:
```
We are keeping the default provider registry as terraform's own registry for now instead
of switching to terraform.
```
Presumably the last word should be OpenTofu?

2024-04-08 16:39 UTC, blgm commented on go.mod
> +	github.com/onsi/ginkgo v1.16.5
Looks like Ginkgo V1 has been re-introduced

2024-04-09 09:53 UTC, pivotal-marcela-campo commented on go.mod
> +	github.com/onsi/ginkgo v1.16.5
fixed

2024-04-09 10:23 UTC, FelisiaM approved these changes

2024-04-09 10:23 UTC, blgm approved these changes

2024-04-09 10:26 UTC, merged