chore: introduce a check for conventional commits on PR messages
cloudfoundry/cloud-service-broker pull request #376
Opened 2022-02-08 16:15 UTC by blgm

We decided as a team to try conventional commits as a way to make the
commit history easier to understand - particularaly when writing release
notes. This filter will nudge folks to get the PR titles right.

### Checklist:

* ~~[ ] Have you added Draft Release Notes in `docs/draft-release-notes.md`?~~
* [X] Have you followed the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)?

2022-02-08 17:05 UTC, pivotal-marcela-campo requested changes

2022-02-08 17:05 UTC, pivotal-marcela-campo commented on .github/workflows/conventional-commit.yml
> +            const allowed = ["feat\\!", "feat", "fix", "chore", "docs", "build"]
do we want to add "test" to the list? or would we start tagging them with "chore"?

2022-02-08 17:12 UTC, blgm commented on .github/workflows/conventional-commit.yml
> +            const allowed = ["feat\\!", "feat", "fix", "chore", "docs", "build"]
Yes we do! Added.

2022-02-09 09:23 UTC, pivotal-marcela-campo approved these changes

2022-02-09 13:37 UTC, merged