test: add broker unbind test
cloudfoundry/cloud-service-broker pull request #430
Opened 2022-03-18 15:06 UTC by jimbo459

### Checklist:

~* [ ] Have you added Draft Release Notes in `docs/draft-release-notes.md`?~
* [x] Have you followed the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)?

2022-03-18 15:39 UTC, FelisiaM commented on brokerapi/broker/unbind_test.go
> +			Expect(response).To(BeZero())
Technically correct, but it would be better to be nil

2022-03-18 15:44 UTC, FelisiaM commented on brokerapi/broker/unbind_test.go
> +			Expect(fakeServiceProvider.UnbindCallCount()).To(Equal(1))
Personal preference - but I would say here is a good opportunity to validate that unbind is being called with the expected args - instanceid and binding id)
Pro: For me this is important for calls to functions that accept a list of strings like this one, because it a the type of call where one can easily put the args in the wrong order since they are all just strings. 
Cons:
- one can say there will be integration tests that should fail if the args are in the wrong order (might be true but this codebase is weird)
- it makes refactoring that includes changing signatures more complex. Again in this codebase I don't see that happening anytime soon

2022-03-18 16:52 UTC, FelisiaM commented on brokerapi/broker/unbind_test.go
> +					Plans: []pkgBroker.ServicePlan{
nitpick: There is quite a long setup to this service - I would suggest you remove things from the setup that do not change the behaviour of the test. E.g `ProvisionInputVariables` are not really used in unbind.
For me this helps make it clear what is setup intentionally

2022-03-18 16:53 UTC, FelisiaM commented on brokerapi/broker/unbind_test.go
> +		It("should remove binding from database", func() {
There is another use case of unbinding when credhub is enabled - did you intentionally leave it out because it's not straightforward to test or was is an oversight?

2022-03-18 16:57 UTC, FelisiaM commented on brokerapi/broker/unbind_test.go
> +
One area that is not tested is the bind variables - this is a bit of a tricky one because not all of it can be purely unit tested, but I think it is worth doing a few tests inspired by the deprovision [tests](https://github.com/cloudfoundry/cloud-service-broker/blob/1ee046d61490ce42491c834b5c233a83753351d2/brokerapi/broker/deprovision_test.go#L132-L178)

2022-03-18 16:59 UTC, FelisiaM requested changes
I added a few comments - some are just opinions (that you can ignore) and some are missing test cases.

Overall I think is so much improvement from what was already there.

Also, dot forget to remove the old test from `broker_test.go` as part of this PR

2022-03-22 08:25 UTC, jimbo459 commented on brokerapi/broker/unbind_test.go
> +			Expect(response).To(BeZero())
I think this one does need to expect to be zero as a struct is returned with `zero` values ([see docs](https://go.dev/ref/spec#The_zero_value)). 
Asserting to equal nil fails as a struct is returned, just with zero values.

2022-03-22 08:25 UTC, jimbo459 commented on brokerapi/broker/unbind_test.go
> +			Expect(fakeServiceProvider.UnbindCallCount()).To(Equal(1))
Agreed - good catch

2022-03-22 08:38 UTC, jimbo459 commented on brokerapi/broker/unbind_test.go
> +		It("should remove binding from database", func() {
I have added assertions that the credstore methods have been invoked and the correct amount of times. Faking the arguments they're called with is not really possible with the current implementation, but this feels like a good catch to ensure those methods are being called.

2022-03-22 14:47 UTC, jimbo459 commented on brokerapi/broker/unbind_test.go
> +
Thanks - have added some tests around the vars

2022-03-22 17:06 UTC, blgm approved these changes

2022-03-22 17:07 UTC, merged