feat: terraform upgrades no longer performed on update/delete
cloudfoundry/cloud-service-broker pull request #517
Opened 2022-05-24 14:39 UTC by jimbo459

- This is in preparation of the new workflow where Terraform will
  only by upgraded as part of the maintenance upgrade flow

[#182209076](https://www.pivotaltracker.com/story/show/182209076)

### Checklist:

* [ ] Have you added or updated tests to validate the changed functionality?
* [ ] Have you added Draft Release Notes in `docs/draft-release-notes.md`?
* [ ] Have you followed the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)?

2022-05-24 15:32 UTC, FelisiaM commented
I think the behaviour change should be included in the docs release notes as well. Last release notes say that delete/unbind can do upgrade as well

2022-05-24 15:40 UTC, FelisiaM commented on pkg/providers/tf/update.go
> -		err = provider.performTerraformUpgrade(ctx, workspace)
is this an early optimisation? Just thinking that there is a store to split the upgrade flow and that will need to implement the terraform upgrade. By removing it it means we have to rewrite the same code and tests again instead of just moving them around

2022-05-24 15:45 UTC, FelisiaM commented on pkg/providers/tf/provider.go
> +func (provider *TerraformProvider) checkTerraformVersion(ctx context.Context, workspace workspace.Workspace) error {
context is no longer being used or needed here

2022-05-24 15:49 UTC, FelisiaM commented on pkg/providers/tf/provider.go
> +		return errors.New("apply attempted with a newer version of terraform than the state")
Is this essentially implementing part of the next story about blocking all interactions with the delete/unbind https://www.pivotaltracker.com/story/show/182208954 ?

2022-05-24 15:54 UTC, FelisiaM commented on pkg/providers/tf/provider.go
> +		err = provider.checkTerraformVersion(ctx, workspace)
I think this check should not be be in the goroutine. The check should be done as soon as we get the workspace and fail fast as part of the initial response, not as a last operation failure.
There is another question in my mind about what error should be returned. I think the message should mention a tip to run upgrade-service, but possible also respond with a `MaintenanceInfoConflict` error

2022-05-24 15:55 UTC, jimbo459 commented on pkg/providers/tf/update.go
> -		err = provider.performTerraformUpgrade(ctx, workspace)
The spike has all the code / tests. We essentially need to remove the upgrade from update in its current position before starting on the upgrade flow. 
This felt like a clean way to reset us back to a clean state where there is no upgrade performed, but the code is archived to be used in the actual implementation.

2022-05-24 15:55 UTC, FelisiaM requested changes
Left some comments

2022-05-24 15:58 UTC, jimbo459 commented on pkg/providers/tf/provider.go
> +		return errors.New("apply attempted with a newer version of terraform than the state")
I was going to strip all this out, but we have now exposed the ability to add multiple Terraform Binaries to a Brokerpak. It felt a little dangerous to remove this step, given that it already existed, but just remove the upgrade logic. 
You're right that story will essentially result in the same behaviour, but fail at an earlier point in the flow.

2022-05-24 15:59 UTC, jimbo459 commented on pkg/providers/tf/provider.go
> +		err = provider.checkTerraformVersion(ctx, workspace)
Yeah - in my mind this would all be done as part of https://www.pivotaltracker.com/story/show/182208954. This chore was simply stripping out the upgrade behaviour and leaving the rest of the current logic untouched, with a view that it will all be solved in that story.

2022-05-24 16:00 UTC, FelisiaM commented on pkg/providers/tf/update.go
> -		err = provider.performTerraformUpgrade(ctx, workspace)
Being realistic,  maybe it's enough to just added a link to this change in the next story so its easy to find.

2022-05-24 16:18 UTC, FelisiaM commented on pkg/providers/tf/update.go
> -		err = provider.performTerraformUpgrade(ctx, workspace)
Maybe the part that might not be clear is that update path would not be exercised anymore so there is no need for this check here at all. 
Update and upgrade go through the same endpoint and also maintenance info is always passed by CF.

2022-05-25 08:16 UTC, closed without merging

2022-05-25 08:17 UTC, jimbo459 commented
Closing as we will play story https://www.pivotaltracker.com/story/show/182208954 which will cover this functionality.