chore: factor out brokerpack packer from testdrive package
cloudfoundry/cloud-service-broker pull request #680
Opened 2022-11-25 18:20 UTC by blgm

The 'testdrive' package is shared between integration tests and the CSB local experience. But the brokerpak builder was used only by the integration tests. So this part of the package has been moved to become a test helper for the integration tests, keeping the testdrive package more focused.

2022-11-28 11:45 UTC, jhvhs requested changes

2022-11-28 11:45 UTC, jhvhs commented on integrationtest/info_endpoint_test.go
> +		var err error
**nitpick**: extra var declaration can be avoided via use of `must` helper.

2022-11-29 09:52 UTC, blgm commented on integrationtest/info_endpoint_test.go
> +		var err error
Absolutely. That's updated.

2022-11-29 12:21 UTC, jhvhs approved these changes

2022-11-29 12:22 UTC, merged